### ISSUE TITLE
Mandrill - Wishlist Items

### ISSUE THREAD

**Issue by thebimman** [BadMonkeysTeam/Mandrill#15]
Firstly thank you Konrad!

Secondly can we please get some improvements (or know-how on how to achieve the below if already features of Mandrill)
- Precise numbering (a display option) labels above the data columns in the graphs
- Ability to control the width of the data column in a graph
- Ability to rotate or set the text orientation for the labels on the Axis' in the graphs
  ![mandrill - user request or wishlist](https://cloud.githubusercontent.com/assets/10429157/19459548/488c70f8-9530-11e6-8101-1e13d85647fe.PNG)

Refer attached pic for more details

Cheers

Jason

**Comment by ksobon** [comment]
Jason, 
Next release will have ability to control the orientation of the text in the bar chart. 

https://github.com/ksobon/Mandrill/issues/8

To control the width of the bars you need to make the bar chart width smaller. Individual bars are equally spaced along the entire width. 

The last thing is ability to turn on the actual value for each bar. These values show up when you hover over the bar. Do you want them to persist, so you can print them?

**Comment by ksobon** [comment]
It should look like this with the new text rotation: 

![image](https://cloud.githubusercontent.com/assets/529781/19493056/241cfbb8-9547-11e6-9931-c15570cd20e5.png)

I also had to add Bottom Margin control so that your text doesn't get cropped off.

**Comment by thebimman** [comment]
Nice work! Is it published yet?

Jason Howden

Director | Vice President Software Development

RTV Tools Limited

email: jason@rtvtools.com
tel: +64 21 145 3979
skype: jason.howden
web: www.rtvtools.com

[sent by iphone]

**Comment by ksobon** [comment]
No, this is not published yet. I need to do some more cleanup on some of these charts based on feedback as well as incorporate the license from EO now that I got funding for it. 

I am also adding something that you showed me in your last email: 

![image](https://cloud.githubusercontent.com/assets/529781/19520336/e70514d0-95dd-11e6-9b14-5c721ccfee13.png)

It's all coming, at some point. :-)

**Comment by thebimman** [comment]
Awesome - thank you!

We are loving Mandrill 

Jason Howden

Director | Vice President Software Development

RTV Tools Limited

email: jason@rtvtools.com
tel: +64 21 145 3979
skype: jason.howden
web: www.rtvtools.com

[sent by iphone]

**Comment by ksobon** [comment]
Also bar chart will now have an option for adding a label above the bar that displays the actual value. This will be published with the next release of Mandrill. 

![image](https://cloud.githubusercontent.com/assets/529781/21693295/62ca7396-d34e-11e6-952c-afc1c387a27c.png)
