### ISSUE TITLE
System.IO.FileLoadException notification

### ISSUE THREAD

**Issue by makotoohura** [BadMonkeysTeam/Mandrill#26]
Hi,
When I installed Archi-lab_Mandrill package to Dynamo for Revit, I received four notifications in Dynamo.
![error1](https://cloud.githubusercontent.com/assets/24534933/21123511/84c6dd8e-c11c-11e6-922d-a8d76c767f69.jpg)
The following is the detail.
![error2](https://cloud.githubusercontent.com/assets/24534933/21123521/934f4ada-c11c-11e6-8eed-be583c420f7b.jpg)
![error3](https://cloud.githubusercontent.com/assets/24534933/21123523/95f0a586-c11c-11e6-83fa-67a92885bfff.jpg)

Although I uninstalled Insight 360 addin, the notification isn't gone. When I uninstalled Archi-lab_Mandrill package, the notification is gone.

The following is my environment.
- Revit 2017.1 Japanese (17.0.1.099.0, 20161117_1200(x64), 2017.1.1)
- Dynamo 1.2.1 (Dynamo Core 1.2.1.3083, Dynamo Revit 1.2.1.3083)
- Archi-lab_Mandrill (2017.12.3)
- Windows 8.1 Pro Japanese, Windows 10 Pro Japanese

Please let me know if you have any workaround.
Thanks,
Makoto

**Comment by ksobon** [comment]
It seems to me that you might have an issue with an older version of the Mandrill getting improperly updated to a newer one. Do you by any chance have more than one version of Dynamo installed? This might also be causing this issue especially if they have multiple versions of Mandrill installed. Try uninstalling and DELETING all source files for Dynamo and installing it fresh. Then go ahead and install Mandrill and report back. 

Cheers !

**Comment by makotoohura** [comment]
Hi Konrad-san,
Thank you for replying.
I uninstalled all Revit and Dynamo. Then deleted all folders for Revit and Dynamo.

I installed Revit 2017 (17.0.416.0, 20160225_1515(x64)) and Dynamo 1.2.1 again.
Then I installed Archi-lab_Mandrill (2017.12.3).
I didn't receive any notification in Dynamo.

However, after I updated Revit to 2017.1.1 Fixes (17.0.1.099.0, 20161117_1200(x64), 2017.1.1), I receive the four notification in Dynamo. Mandrill may be conflicted Revit 2017.1.1.

Thanks,
Makoto

**Comment by ksobon** [comment]
so what happens when you update Revit to 2017.1 is that it installs Dynamo again. I would do this in this sequence. 

1. Uninstall Dynamo and delete all folders. It will have folders in Program Files and users/username/Roaming/Dynamo etc. Please delete them all. 
2. Install a fresh version of Dynamo 1.2. 

The trick is that Dynamo doesn't work when there are multiple versions of it installed. When you installed a Revit update that also installed an older version of dynamo and is causing all the issues.

**Comment by makotoohura** [comment]
Hi,
I tried the following step:
1. uninstall Archi-lab_Mandrill
2. uninstall Dynamo Revit and Dynamo Core
3. Delete C:\Program Files\Dynamo, C:\ProgramData\Dynamo and C:\Users\name\AppData\Roaming\Dynamo
4. Install Dynamo 1.2.1
5. Install Archi-lab_Mandrill

I received the notification again.

Thanks,
Makoto

**Comment by ksobon** [comment]
There is a conflict with one of the installed packages that use the same library as Mandrill. Revit is the worst at just loading all of the DLLs into the same context. I don't know what plug-in you have installed that uses the same library (EO.WebBrowser) that mine does, but you would have to uninstall one of them for the other to work with Revit.

**Comment by ksobon** [comment]
so I have narrowed it down now. When I install Revit 2017.1 it displays these notifications. I did check if Mandrill runs and have no issues. Can you check if mandrill actually works on your machine. This might be ignorable.

**Comment by makotoohura** [comment]
Hi,
Yes, I could create Bar and Pie chart in the window if I received the notification.
However, I cannot create the PDF file by "Print to PDF" node. When I click "Print Window" button, Dynamo is always crashed.
The following is the graph and capture.
[test.zip](https://github.com/ksobon/Mandrill/files/659797/test.zip)
![capture](https://cloud.githubusercontent.com/assets/24534933/21298037/d41171c8-c5cd-11e6-9cbd-34204a7b415c.png)
![dynamocrashed](https://cloud.githubusercontent.com/assets/24534933/21298038/dae558ac-c5cd-11e6-98df-36f01e6e526d.jpg)

Because Dynamo Studio is also crashed by this graph, this issue may not be relationship with this notification.

Thanks,
Makoto

**Comment by ksobon** [comment]
if you could post that warning message so that I can read the whole thing that would help. Right now I am only seeing part of the warning and its not helping. 

Also, Mandrill works just fine on my machine. I am not using Dynamo Studio. I am using Dynamo for Revit or Dynamo Sandbox. It prints fine and the window gets displayed fine too. This must be an issue with your set-up.

**Comment by makotoohura** [comment]
Hi,
I attached the error message detail.
[error detail.zip](https://github.com/ksobon/Mandrill/files/659835/error.detail.zip)
I received this error on Dynamo for Revit and Dynamo Studio.
Thanks,
Makoto

**Comment by ksobon** [comment]
So something is `null`, can I see the values for Style, FilePath and Report?

**Comment by ksobon** [comment]
@makotoohura this should be fixed. I think it was because you were missing a DLL called HtmlAgilityPack and that was fixed in the latest issue: 2018.0.1 The notifications above don't actually cause any issues.

**Comment by wassimj** [comment]
Just to add that I noticed the same notification when I started Dynamo from within Revit, but not when just using the Sandbox:

While loading assembly Mandrill_UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, Dynamo detected that the dependency EO.WebBrowser, Version=16.2.50.0, Culture=neutral, PublicKeyToken=e92353a6bf73fffc was already loaded with an incompatiable version. It is likely that another Revit Addin has loaded this assembly, please try uninstalling other Addins, and starting Dynamo again. Dynamo may be unstable in this state.
It is likely one of the following assemblies loaded the incompatible version:
EnergyAnalysis, EO.WebBrowser, EO.WebBrowser
