### ISSUE TITLE
Barchart not visible

### ISSUE THREAD

**Issue by cesarecaoduro** [BadMonkeysTeam/Mandrill#33]
I'm facing problem with barchart based charts. All others a re just working fine but barchart is not visible in the dashboard. No errors in the workflow and now warnings. 
Revit all versions, Dynamo 1.2.1

**Comment by ksobon** [comment]
Can you please post a screenshot of your setup or even better your Dynamo file and any Excel/CSV files? I will have to be able to see the issue or recreate it in order to help.

**Comment by cesarecaoduro** [comment]
![2017-04-20 08_45_46-dynamo](https://cloud.githubusercontent.com/assets/26373891/25215398/d452102e-25a5-11e7-8529-3d3f05c7c240.jpg)

**Comment by ksobon** [comment]
Try setting the input for "TickMarkX" to 3

**Comment by ksobon** [comment]
@cesarecaoduro it has been a while since I heard from you. I am going to assume that this was resolved.
