### ISSUE TITLE
Assigning colors to values

### ISSUE THREAD

**Issue by DanielHurtubise** [BadMonkeysTeam/Mandrill#34]
I'm trying to get each bar in a Bar Chart to use a different color.
I use a Color.Range Node and fed it into the Bar Color input but no luck.
I also want to be able to use the same combination(value/color) for more chart to keep it consistent.

Thanks

**Comment by ksobon** [comment]
That functionality only exists in the Horizontal Bar Chart at the moment. Regular bar chart has single color. I will put that down as a feature request.

**Comment by DanielHurtubise** [comment]
I was under the impression that this would work
![image](https://cloud.githubusercontent.com/assets/4299930/26210906/64a50eea-3bf1-11e7-975d-fecb53f4dfb9.png)

**Comment by ksobon** [comment]
This will: 

![image](https://cloud.githubusercontent.com/assets/529781/26219631/adcf2718-3bdd-11e7-94e0-0167680c01b9.png)

Reason why is because D3 charts assign colors to bars by properties of data. So you can say color each bar by its value X, which in this case is the input Color on data node.

**Comment by ksobon** [comment]
@DanielHurtubise so this would actually work, just follow my image.
