### ISSUE TITLE
Keeping the Window on top

### ISSUE THREAD

**Issue by DanielHurtubise** [BadMonkeysTeam/Mandrill#36]
When minimizing Dynamo the report Window also minimizes. Is it possible to keep it on top?
I can deal with the issue as i have 3 monitors but most people don't.

**Comment by ksobon** [comment]
This is because Dynamo is the owner window of Mandrill window. Minimizing the owner will automatically minimize the child. I will see if I can break that relationship.

**Comment by ksobon** [comment]
@DanielHurtubise sorry but I can't seem to be able to change this behavior.
