### ISSUE TITLE
A license is needed to continue using this product

### ISSUE THREAD

**Issue by vertragus** [BadMonkeysTeam/Mandrill#38]
![untitled-1](https://user-images.githubusercontent.com/23382643/27288933-8a68e8ce-5508-11e7-8d2c-ffc90272bd71.jpg)

**Comment by ksobon** [comment]
Thank you for reporting. I am aware of this, will get the license renewed, ASAP and post an update. Apologies for the inconvenience.

**Comment by ksobon** [comment]
@vertragus OK, so I am afraid it isn't me forgetting to extend my license. It's good trough October. It also seems to be working just fine on my machine: 

![image](https://user-images.githubusercontent.com/529781/27296963-04f53826-54f1-11e7-8c8b-7c7ae8ace828.png)

Can you make sure that you have this file and it's not blocked: 

![image](https://user-images.githubusercontent.com/529781/27297037-427dc226-54f1-11e7-93e6-11fbae6d3a86.png)

**Comment by vertragus** [comment]
It works fine now. Thank you!
