### ISSUE TITLE
dynamo crashed using html/pdf output

### ISSUE THREAD

**Issue by Phlipflops** [BadMonkeysTeam/Mandrill#39]
First of all: Thanks for the package! Its saving my ass right now visualizing the data I Need to evaluate while working on my Project...  
here is my issue I posted in the wrong repo before: 
If I use the html or pdf Output, Dynamo crashes and give the following Report:

> Could not load file or assembly 'HtmlAgilityPack, Version=1.4.9.5, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a' or one of its dependencies. 

![crashed report](https://user-images.githubusercontent.com/29751762/27678848-f71e486e-5cb6-11e7-89fe-97691fa64e67.PNG) 

Any idea? Thanks!

**Comment by Phlipflops** [comment]
All good I got it:) reinstalled the agilitypack. Its working fine right now:)

**Comment by ksobon** [comment]
There should be a dll named HtmlAgilityPack in Mandrill's package folder under bin. Can you please check its there?

**Comment by Phlipflops** [comment]
It wasn`t there. Now it is and everything is fine! Thank you @ksobon!
