### ISSUE TITLE
Error in building: Authentication and xcopy /Q/Y

### ISSUE THREAD

**Issue by huythach** [BadMonkeysTeam/Mandrill#40]
Thank you very much for sharing this great app.

I can download and install Mandrill from Package Manager, however, I am unlucky on building this package from source code with 2 errors:

1. Authentication error as the attached image. I think the reason is that I don't have Mandrill_License.dll file, so I unzip Mandrill.zip file inside _Builds/Grasshopper folder then added this DLL file to project in the Visual Studio. I built the project again, but the second bug occurs.
![no_authentication](https://user-images.githubusercontent.com/11055389/28193611-0a666c76-6879-11e7-8156-addbb6742d87.png)

2. xcopy /Q/Y bug:
![build_bug](https://user-images.githubusercontent.com/11055389/28193681-8d077b3e-6879-11e7-8a6e-c3f1cbdebb02.png)

**Comment by radumg** [comment]
@ksobon , sorry for butting in, just randomly saw this in my feed :smile:  .

Hi @huythach , please check the[ post-build section of the projects](https://github.com/BadMonkeysTeam/Mandrill/blob/master/Mandrill/Mandrill_Dynamo.csproj#L699) :  the `xcopy` script is trying to copy files to this directory :
C:\Users\`ksobon`\AppData\Roaming\Dynamo\... 
which will obviously not exist on your machine. Those paths need to be updated with your correct user paths.

Perhaps @ksobon can replace those hard-coded paths with flags like `%userdir%` so future contributors don't get the error ?

**Comment by ksobon** [comment]
Yeah that's the issue. I will be doing a little work on Mandrill maybe next month. I can pick that up then.

**Comment by huythach** [comment]
@radumg: thank you very much for pointing it out.
