### ISSUE TITLE
Difference between Online Package and importing DLL file

### ISSUE THREAD

**Issue by huythach** [BadMonkeysTeam/Mandrill#41]
There are some differences in Report component when installing Archi-lab_Mandrill from the Online Package and importing Archi-lab_Mandrill.dll file after building the source code project.
As in the attached images, when I install Mandrill from the Online Package, the Report component contains 3 parts: Html, Pdf and Window. However, when I build your source code project, then import Archi-lab_Mandrill.dll file (from Mandrill/bin/Release) to Dynamo, the Report component contains only 1 part: Pdf.

Is there anything wrong in my file importing? Or the Mandrill from the Online Package is newer than the one from the source code?

![archi-lab_mandrill_onlinepackage](https://user-images.githubusercontent.com/11055389/29152298-a48469b8-7dc1-11e7-8183-4803c4c9bef6.png)

![archi-lab_mandrill_importdllfile](https://user-images.githubusercontent.com/11055389/29152305-b37a1314-7dc1-11e7-87f6-188f87dd9986.png)

**Comment by ksobon** [comment]
Source will be a little ahead of what is posted on the Package Manager and Food4Rhino sites. I might have been testing a thing or two recently.
