### ISSUE TITLE
Archi-lab_Mandril version 2018.0.1 Create Report Node issue

### ISSUE THREAD

**Issue by TheBIMsider** [BadMonkeysTeam/Mandrill#46]
Hello, I just installed the new Mandrill Package 2018.0.1 and it seems the "create report" node is missing the report output now, am I missing something? I'm currently using Revit 2018.2 and Dynamo 1.3.2.

Thanks, Carl

![2018-03-27_19-24-06](https://user-images.githubusercontent.com/37883693/38056350-7cc7f15a-3299-11e8-8151-ebb5926278c6.png)
![2018-03-27_19-22-34](https://user-images.githubusercontent.com/37883693/38056359-818f5642-3299-11e8-8906-e8cb02273c0f.png)

**Comment by ksobon** [comment]
Should be fixed: 
![image](https://user-images.githubusercontent.com/529781/38067544-076bc9da-32db-11e8-85d2-ae69bb1eb6c5.png)
