### ISSUE TITLE
Dynamo 2.0 issues

### ISSUE THREAD

**Issue by Eckart-S** [BadMonkeysTeam/Mandrill#47]
I had a quick check of Mandrill package with Dynamo 2.0 release version and found the following issues:
(Dynamo Sandbox 2.0 / Dynamo for Revit (2017))

- Create Report node does not appear at all
- Report Window node can be placed but after saving + opening its gone
- Save to Html / Print to PDF node can be placed but when file is saved it freezes dynamo
- Font Style / Font Weight / Front Transformation node can be placed but after saving + opening it duplicates their ports and makes them unusable (error message) 

Best regards, Eckart

**Comment by ksobon** [comment]
This was just updated and released. Please download from package manager.
