### ISSUE TITLE
Simple Bar Chart

### ISSUE THREAD

**Issue by DanielHurtubise** [BadMonkeysTeam/Mandrill#49]
Can't figure out why i get an empty Window

![image](https://user-images.githubusercontent.com/4299930/39518916-fe60654a-4e04-11e8-8a66-352234c6e79b.png)

**Comment by ksobon** [comment]
Try this: 

![image](https://user-images.githubusercontent.com/529781/39578030-078f93aa-4eb1-11e8-8022-853cd69b6f77.png)

**Comment by ksobon** [comment]
@DanielHurtubise did my suggestion help?

**Comment by DanielHurtubise** [comment]
Sorry for the delay, yes it id ;)
Thanks a lot
