### ISSUE TITLE
Domain of ScatterPlot X-axis

### ISSUE THREAD

**Issue by wassimj** [BadMonkeysTeam/Mandrill#56]
The X-Axis domain for the scatterplot chart seems wrong. If I set the domain to A=0, B=1, I get -1 to 1. If I set it to  A=1 B=1, then I get the correct 0 to 1 domain . The Y-axis domain is correct.

<img width="1236" alt="mandrill-bug" src="https://user-images.githubusercontent.com/6302909/52668633-f7cc0700-2f0b-11e9-9694-c6073397a7f1.PNG">

**Comment by ksobon** [comment]
@wassimj you are correct. There was a mistake in my code that was causing it. it should be fixed now. 

![image](https://user-images.githubusercontent.com/529781/69916120-d4cffc80-1424-11ea-8f1a-44ea1f059a35.png)

![image](https://user-images.githubusercontent.com/529781/69916129-05179b00-1425-11ea-8190-d99387b440e6.png)
